### ISSUE TITLE
Pepe meme not really ok to use...

### ISSUE THREAD

**Issue by everythingIO** [roots/trellis-docker#2]
Please be aware of the connotation of the Pepe meme as neo-nazi mascot.

http://www.adl.org/combating-hate/hate-on-display/c/pepe-the-frog.html

**Comment by scherii** [comment]
>[…] The mere fact of posting a Pepe meme does not mean that someone is racist or white supremacist. [...]

**Comment by swalkinshaw** [comment]
I didn't even realize the image *was* "Pepe" (which I'm aware of). I viewed it as part of the http://knowyourmeme.com/memes/feels-good-man meme which I've been using forever and well before any of the Pepe/nazi stuff.

So for the record: I'm absolutely against anything related to neo-nazism (including any other name they try to go by) and I completely disagree with everything they stand for.

This entire repo was a joke anyway and since that image could misrepresent Roots, I'm just taking down the whole thing.
